spring:
      datasource:
          driver-class-name: com.mysql.jdbc.Driver
#          url: jdbc:mysql://192.168.10.102/tl
          url: jdbc:mysql://192.168.10.156:3306/tl
          username: root
          password: 123456

      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
