spring:
      datasource:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1/tl
          username: root
          password: hjq951019

      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
